/* Generated by $audit-static-research-site. Do not edit by hand. */
(function(){
  "use strict";
  const ROUTES={};
  const script=document.currentScript;
  const root=new URL("./",script.src);
  function keyFor(url){
    const rootPath=decodeURIComponent(root.pathname).replace(/\/$/,"")+"/";
    const path=decodeURIComponent(url.pathname);
    return path.startsWith(rootPath)?path.slice(rootPath.length):null;
  }
  function routeAnchor(a){
    if(a.dataset.viewerRouted||a.classList.contains("openmd")||a.hasAttribute("data-raw-download"))return;
    const raw=a.getAttribute("href");
    if(!raw||raw.startsWith("#"))return;
    let url;try{url=new URL(raw,document.baseURI);}catch(_err){return;}
    if(!url.pathname.toLowerCase().endsWith(".md"))return;
    const route=ROUTES[keyFor(url)];if(!route)return;
    a.href=new URL(route.index+(route.id?"#"+route.id:""),root).href;
    a.removeAttribute("target");a.removeAttribute("rel");a.dataset.viewerRouted="true";
  }
  function scan(node){
    if(node.nodeType!==1)return;
    if(node.matches&&node.matches("a[href]"))routeAnchor(node);
    if(node.querySelectorAll)node.querySelectorAll("a[href]").forEach(routeAnchor);
  }
  scan(document.documentElement);
  new MutationObserver(records=>records.forEach(r=>r.addedNodes.forEach(scan))).observe(document.documentElement,{childList:true,subtree:true});
  window.SiteDocumentRoutes=Object.freeze(ROUTES);
})();
